import type { PdfDocument } from "./types";

// TEMPORARY hardcoded data so the admin UI can be built and reviewed before
// the /api/admin/pdfs endpoints exist. Swap this out for a real fetch in
// page.tsx once the backend + Prisma model (e.g. `pdf_documents`) is ready —
// see the `pdfService` TODOs in page.tsx.
export const INITIAL_PDFS: PdfDocument[] = [
  {
    id: "pdf_19ntrca_syllabus",
    title:
      "১৯তম শিক্ষক নিবন্ধন (NTRCA) সম্পূর্ণ সিলেবাস — স্কুল ও কলেজ পর্যায়",
    description:
      "স্কুল ও কলেজ পর্যায়ের বাংলা, English, গণিত ও সাধারণ জ্ঞান — প্রতিটি বিষয়ের টপিক ধরে ধরে সাজানো প্রিন্টযোগ্য সিলেবাস।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/19th-ntrca-syllabus.pdf",
    docType: "SYLLABUS",
    subExamCategoryId: "cmnv745hc000huxikxavri5d3",
    subject: "সকল বিষয়",
    examName: "19th NTRCA",
    tags: ["NTRCA", "সিলেবাস", "১৯তম"],
    fileSizeKb: 860,
    pageCount: 12,
    downloadCount: 4210,
    viewCount: 9830,
    likeCount: 612,
    commentCount: 3,
    isFeatured: true,
    isActive: true,
    isFree: true,
    createdAt: "2026-06-03T14:25:57.522Z",
    updatedAt: "2026-06-03T14:25:57.522Z",
  },
  {
    id: "pdf_dss_syllabus",
    title: "সমাজসেবা অধিদপ্তর (DSS) নিয়োগ পরীক্ষার সিলেবাস",
    description:
      "MCQ ও লিখিত উভয় ধাপের সিলেবাস, প্রতি বিষয়ে ২৫ নম্বর হিসেবে মোট ১০০ নম্বরের বিস্তারিত বিভাজন।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/dss-syllabus.pdf",
    docType: "SYLLABUS",
    subExamCategoryId: "cmpyvd9m70001uxgcoxb7tx5f",
    subject: "সকল বিষয়",
    examName: "সমাজসেবা অধিদপ্তর",
    tags: ["DSS", "সিলেবাস", "সরকারি চাকরি"],
    fileSizeKb: 640,
    pageCount: 8,
    downloadCount: 1180,
    viewCount: 3040,
    likeCount: 145,
    commentCount: 0,
    isFeatured: false,
    isActive: true,
    isFree: true,
    createdAt: "2026-06-04T04:42:22.276Z",
    updatedAt: "2026-06-04T05:08:13.814Z",
  },
  {
    id: "pdf_ntrca_routine_week1",
    title: "NTRCA প্রস্তুতি রুটিন — সপ্তাহ ০১ (সন্ধি বিচ্ছেদ)",
    description:
      "স্বরসন্ধি, ব্যঞ্জনসন্ধি ও বিসর্গসন্ধির নিয়ম অনুশীলনের জন্য দৈনিক রুটিন। উৎস: নবম-দশম শ্রেণির বাংলা ব্যাকরণ (NCTB)।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/ntrca-routine-week-01.pdf",
    docType: "ROUTINE",
    subExamCategoryId: "cmnv745hc000huxikxavri5d3",
    subject: "বাংলা",
    tags: ["রুটিন", "সন্ধি", "NTRCA"],
    fileSizeKb: 420,
    pageCount: 3,
    downloadCount: 2570,
    viewCount: 5120,
    likeCount: 298,
    commentCount: 0,
    isFeatured: false,
    isActive: true,
    isFree: true,
    createdAt: "2026-04-25T04:27:59.934Z",
    updatedAt: "2026-06-04T04:25:46.990Z",
  },
  {
    id: "pdf_ntrca_question_set_01",
    title: "প্রশ্নসেট ০১ — সন্ধি বিচ্ছেদ ও সন্ধির নিয়ম (প্রিন্ট ভার্সন)",
    description:
      "বিগত ১০ম–১৮তম NTRCA পরীক্ষার গুরুত্বপূর্ণ প্রশ্নসমাধানসহ ২৫ নম্বরের প্রশ্নসেট।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/ntrca-question-set-01.pdf",
    docType: "QUESTION_BANK",
    subExamCategoryId: "cmnv745hc000huxikxavri5d3",
    subject: "বাংলা",
    tags: ["প্রশ্নসেট", "সন্ধি", "NTRCA"],
    fileSizeKb: 980,
    pageCount: 6,
    downloadCount: 1890,
    viewCount: 4460,
    likeCount: 210,
    commentCount: 0,
    isFeatured: false,
    isActive: true,
    isFree: false,
    createdAt: "2026-04-25T04:27:59.934Z",
    updatedAt: "2026-06-04T04:25:47.146Z",
  },
  {
    id: "pdf_bcs_50_bangla_previous",
    title:
      "৫০তম বিসিএস প্রিলিমিনারি — বাংলা ভাষা ও সাহিত্য (প্রশ্ন ও ব্যাখ্যা)",
    description:
      "৫০তম বিসিএস প্রিলিমিনারিতে আসা বাংলা ভাষা ও সাহিত্যের প্রতিটি প্রশ্নের বিস্তারিত ব্যাখ্যাসহ সমাধান — সাহিত্য, সন্ধি, ধ্বনি ও বর্ণ থেকে পুঁথি সাহিত্য পর্যন্ত।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/50th-bcs-bangla-solution.pdf",
    docType: "PREVIOUS_QUESTIONS",
    subExamCategoryId: "cmnv745290005uxikq56hsyxc",
    subject: "বাংলা ভাষা ও সাহিত্য",
    examName: "৫০তম বিসিএস",
    tags: ["বিসিএস", "৫০তম", "বিগত প্রশ্ন"],
    fileSizeKb: 1840,
    pageCount: 24,
    downloadCount: 6720,
    viewCount: 15230,
    likeCount: 940,
    commentCount: 2,
    isFeatured: true,
    isActive: true,
    isFree: false,
    createdAt: "2026-04-24T08:25:25.058Z",
    updatedAt: "2026-08-01T01:11:25.841Z",
  },
  {
    id: "pdf_only_ict_guide",
    title: "Only ICT — সরকারি চাকরির পরীক্ষার জন্য সম্পূর্ণ গাইড",
    description:
      "বিভিন্ন সরকারি নিয়োগ পরীক্ষায় বারবার আসা তথ্য ও যোগাযোগ প্রযুক্তি (ICT) টপিকের সংকলন।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/only-ict-guide.pdf",
    docType: "BOOK_GUIDE",
    subExamCategoryId: "cmopm6c5u0001uxzgaig4s2gf",
    subject: "ICT",
    tags: ["ICT", "গাইড", "সরকারি চাকরি"],
    fileSizeKb: 5200,
    pageCount: 96,
    downloadCount: 3110,
    viewCount: 7040,
    likeCount: 402,
    commentCount: 0,
    isFeatured: true,
    isActive: true,
    isFree: false,
    createdAt: "2026-05-03T10:14:47.820Z",
    updatedAt: "2026-05-03T10:14:47.820Z",
  },
  {
    id: "pdf_somas_note",
    title: "বাংলা ব্যাকরণ রিভিশন নোট: সমাস (NCTB ভিত্তিক)",
    description:
      "দ্বন্দ্ব, কর্মধারয়, তৎপুরুষ, বহুব্রীহি, অব্যয়ীভাব ও দ্বিগু সমাসের সংজ্ঞা, উদাহরণ ও নির্ণয়ের কৌশল — এক নজরে।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/somas-revision-note.pdf",
    docType: "NOTES",
    subExamCategoryId: "cmnv745hc000huxikxavri5d3",
    subject: "বাংলা",
    tags: ["সমাস", "ব্যাকরণ", "নোট"],
    fileSizeKb: 310,
    pageCount: 5,
    downloadCount: 2980,
    viewCount: 6110,
    likeCount: 356,
    commentCount: 0,
    isFeatured: false,
    isActive: true,
    isFree: true,
    createdAt: "2026-04-25T04:27:59.934Z",
    updatedAt: "2026-06-04T04:25:47.206Z",
  },
  {
    id: "pdf_free_model_test_1",
    title: "ফ্রি মডেল টেস্ট — দিন ১: বাক্যের শ্রেণিবিভাগ",
    description:
      "বাক্য, বাক্যের গঠন ও বাক্যের শ্রেণিবিভাগ থেকে ২০ নম্বরের প্রিন্টযোগ্য মডেল টেস্ট। উৎস: NCTB নবম-দশম শ্রেণি বাংলা ব্যাকরণ বোর্ড বই।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/free-model-test-day-1.pdf",
    docType: "MODEL_TEST",
    subExamCategoryId: "cmnv745hc000huxikxavri5d3",
    subject: "বাংলা",
    tags: ["ফ্রি", "মডেল টেস্ট"],
    fileSizeKb: 260,
    pageCount: 4,
    downloadCount: 5430,
    viewCount: 11020,
    likeCount: 587,
    commentCount: 0,
    isFeatured: true,
    isActive: false,
    isFree: true,
    createdAt: "2026-08-04T05:36:54.212Z",
    updatedAt: "2026-08-04T05:36:54.212Z",
  },
  {
    id: "pdf_bagdhara_note",
    title: "বাগধারা ও এক কথায় প্রকাশ — দ্রুত রিভিশন শিট",
    description:
      "NTRCA পরীক্ষায় বারবার আসা গুরুত্বপূর্ণ বাগধারা ও বাক্য সংকোচনের তালিকা, দ্রুত রিভিশনের জন্য এক পৃষ্ঠায়।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/bagdhara-revision-sheet.pdf",
    docType: "NOTES",
    subExamCategoryId: "cmnv745hc000huxikxavri5d3",
    subject: "বাংলা",
    tags: ["বাগধারা", "রিভিশন"],
    fileSizeKb: 180,
    pageCount: 2,
    downloadCount: 1650,
    viewCount: 3320,
    likeCount: 168,
    commentCount: 0,
    isFeatured: false,
    isActive: true,
    isFree: true,
    createdAt: "2026-04-25T04:27:59.934Z",
    updatedAt: "2026-06-04T04:25:47.320Z",
  },
  {
    id: "pdf_bcs_job_solution_draft",
    title: "বিসিএস প্রিলিমিনারি জব সল্যুশন — খসড়া সংকলন (অসম্পূর্ণ)",
    description: "সম্পাদনার কাজ চলছে, এখনো প্রকাশের জন্য প্রস্তুত নয়।",
    fileUrl: "https://cdn.farhanmcq.com/pdfs/bcs-job-solution-draft.pdf",
    docType: "QUESTION_BANK",
    subExamCategoryId: "cmnv745290005uxikq56hsyxc",
    subject: "সকল বিষয়",
    tags: ["খসড়া"],
    fileSizeKb: 95,
    pageCount: 1,
    downloadCount: 0,
    viewCount: 12,
    likeCount: 0,
    commentCount: 0,
    isFeatured: false,
    isActive: false,
    isFree: false,
    createdAt: "2026-07-28T09:00:00.000Z",
    updatedAt: "2026-07-28T09:00:00.000Z",
  },
];
